on:
  rss:
    # qiita trend
    url: https://qiita.com/popular-items/feed.atom
jobs:
  post:
    name: Post RSS updates to the discord
    runs-on: ubuntu-latest
    steps:
      - name: Fix date format
        id: date
        run: |
          fix_date=$(date -d ${{ on.rss.outputs.pubDate }} "+%B %d, %Y at %I:%M%p")
          echo "::set-output name=fix_date::${fix_date}"
      - name: Post
        run: |
          curl -X POST \
               -H  "Content-Type: application/json" \
               -d '{"content": "**${{ on.rss.outputs.title }}** - ${{ steps.date.outputs.fix_date }} ${{ on.rss.outputs.link }}"}' \
               ${{ secrets.DISCORD_TECH_QIITA_QIITA_TREND }}
