on:
  rss:
    # qiita trend
    url: https://qiita.com/popular-items/feed.atom
jobs:
  tweet:
    name: Post RSS updates to the discord
    runs-on: ubuntu-latest
    steps:
      - name: Generate date
        id: date
        run: |
          fix_date=$(date -d ${{ on.rss.outputs.pubDate }} "+%B %d, %Y at %I:%M%p")
          echo "::set-output name=fix_date::${fix_date}"
