on:
  rss:
    url: |
      https://rsshub-dun-zeta.vercel.app/bilibili/user/bangumi/73658593
    config:
      format: |
        item.content = item.content.replace(/\n/g, "\\n");
        return item;
      skipOnError: true
jobs:
  post:
    name: Notify Discord of new shows on Bilibili
    runs-on: ubuntu-latest
    steps:
      - name: Ext data
        id: ext
        run: |
          description=$(sed "s/<br>.*//g" <<<'${{ on.rss.outputs.content }}')
          img_url=$(sed 's/^.*<img src="//g;s/" referrerpolicy="no-referrer">//g' <<<'${{ on.rss.outputs.content }}')
          echo "::set-output name=description::${description}"
          echo "::set-output name=img_url::${img_url}"
      - name: Post
         run: |
          curl -s \
               -X POST \
               -H "Accept: application/json" \
               -H "Content-Type: application/json" \
               -d '{ "embeds": [{"title": "**${{ on.rss.outputs.title }}**", "description": "${{ steps.ext.outputs.description }}", "url": "${{ on.rss.outputs.link }}", "image": {"url": "${{ steps.ext.outputs.img_url }}"}}]}' \
               "${{ secrets.DISCORD_PRIVATE_BILIBILI_BANGUMI }}"
          sleep 5
