on:
  rss:
    url: https://rsshub.app/bilibili/fav/73658593/766374793
jobs:
  tweet:
    name: Tweet Liked Videos on Bilibili
    runs-on: ubuntu-latest
    steps:
      - name: Generate text
        id: tweet_text
        env:
          title: ${{ on.rss.outputs.title }}
          link: ${{ on.rss.outputs.link }}
        run: |
          fix_title=$(echo "${title}" | sed -e "s/&amp;/\&/g" | sed -e "s/&lt;/</g;s/&gt;/>/g;s/&quot;/\"/g;s/&apos;/'/g")
          text=$(echo "在哔哩哔哩赞过: ${fix_title} ${link} #bilibili #哔哩哔哩 #ビリビリ動画")
          echo "::set-output name=text::${text}"
      - uses: ethomson/send-tweet-action@v1
        with:
          status: "${{ steps.tweet_text.outputs.text }}"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
