on:
  poll:
    url: https://api.github.com/users/redpeacock78/starred?page=1&per_page=20
    requestConfig:
      method: GET
jobs:
  tweet:
    name: Tweet new stock on Qiita
    runs-on: ubuntu-latest
    steps:
      - name: Text tweet
        uses: ethomson/send-tweet-action@v1
        with:
          status: "Starred Repo on Github: ${{ on.poll.outputs.full_name }} ${{ on.poll.outputs.html_url }}"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
