on:
  rss:
    url:
      # 2.5次元の誘惑
      - https://shonenjumpplus.com/rss/series/10834108156661135927
      # 怪獣8号
      - https://shonenjumpplus.com/rss/series/13933686331674116114
      # ゲーミングお嬢様
      - https://shonenjumpplus.com/rss/series/13933686331681118994
      # デッドプール：SAMURAI
      - https://shonenjumpplus.com/rss/series/13933686331761415050
      # デビィ・ザ・コルシファは負けず嫌い
      - https://shonenjumpplus.com/rss/series/13933686331756948776
      # その淑女は偶像となる
      - https://shonenjumpplus.com/rss/series/13933686331775866254
      # ミュータントは人間の彼女とキスがしたい
      - https://shonenjumpplus.com/rss/series/3269754496316031224
      # 神のまにまに
      - https://shonenjumpplus.com/rss/series/3269754496419328842
      # 殺戮の王
      - https://shonenjumpplus.com/rss/series/3269754496535710124
      # ニューワールドオーダー
      - https://shonenjumpplus.com/rss/series/3269632237304433100
      # ココロのプログラム
      - https://shonenjumpplus.com/rss/series/3269754496567812819
      # あらがえ！ダークエルフちゃん
      - https://shonenjumpplus.com/rss/series/3269754496340768651
      # カメリアのカーテン
      - https://shonenjumpplus.com/rss/series/3269754496895767342
      # てるてる建設(株)
      - https://shonenjumpplus.com/rss/series/3270296674387638314
      # 正反対な君と僕
      - https://shonenjumpplus.com/rss/series/3269754496899770329
      # チェンソーマン 第二部
      - https://shonenjumpplus.com/rss/series/3270375685341574005
      # 株式会社マジルミエ
      - https://shonenjumpplus.com/rss/series/3269754496555043134
    config:
      skipOnError: true
      sort:
        link: 1
jobs:
  post:
    name: Post RSS updates to the discord
    runs-on: ubuntu-latest
    steps:
      - name: Fix title
        id: title
        run: |
          fix_title=$(echo "${{ on.rss.outputs.title }}" | sed "s/&amp;/\&/g;s/&lt;/</g;s/&gt;/>/g;s/&quot;/\"/g;s/&apos;/'/g" | sed 's/*/\\\\*/g;s/_/\\\\_/g;s/~~/\\\\~~/g')
          echo "::set-output name=fix_title::${fix_title}"
      - name: Post
        run: |
          curl -s \
               -X POST \
               -H  "Content-Type: application/json" \
               -d '{"content": "**${{ steps.title.outputs.fix_title }}** ${{ on.rss.outputs.link }}"}' \
               ${{ secrets.DISCORD_PRIVATE_MANGA_JUMP_PLUS }}
