on:
  script:
    run: |
      const Parser = require(`${process.env.GITHUB_WORKSPACE}/node_modules/rss-parser/lib/parser.js`);
      const parser = new Parser();
      const result = await helpers.axios.get("http://www.nicovideo.jp/mylist/33014334/64875310?rss=2.0");
      const json = parser.parseString(result.data);
      return json;
    deduplicationKey: link
jobs:
  tweet:
    name: Tweet Liked Videos on Niconico
    runs-on: ubuntu-latest
    steps:
      - name: Generate text
        id: tweet_text
        env:
          title: ${{ on.script.outputs.title }}
          link: ${{ on.script.outputs.link }}
        run: |
          tag=$(echo "${{ on.script.outputs.link }}" | sed -e "s|http://www.nicovideo.jp/watch/|#|" -e "s|?ref=rss_mylist_rss2||")
          fix_link=$(echo "${{ on.script.outputs.link }}" | sed -e "s/?ref=rss_mylist_rss2//")
          text=$(echo "${title} - ニコニコ動画 をマイリストに登録しました。 ${fix_link} #ニコニコ動画 ${tag}")
          echo "::set-output name=text::${text}"
