on:
  poll:
    url:
      # マイリスト2
      - https://feed2json.fly.dev/v1/feed?url=http%3A%2F%2Fwww.nicovideo.jp%2Fmylist%2F73715852%3Frss%3D2.0&count=20
    itemsPath: items
    deduplicationKey: guid
    buildOutputsOnError: true
    config:
      skipOnError: true
jobs:
  tweet:
    name: Tweet Liked Videos on Niconico
    runs-on: ubuntu-latest
    steps:
      - name: Generate text
        id: tweet_text
        env:
          link: ${{ on.poll.outputs.link }}
        run: |
          fix_link=$(echo "${link}" | sed -e "s/?ref=rss_mylist_rss2//")
          tag=$(echo "${link}" | sed -e "s|http://www.nicovideo.jp/watch/|#|" -e "s|?ref=rss_mylist_rss2||")
          text=$(echo "${{ on.poll.outputs.title }} - ニコニコ動画 をマイリストに登録しました。 ${fix_link} ${tag} #ニコニコ動画")
          echo "::set-output name=text::${text}"
      - name: Text tweet
        uses: ethomson/send-tweet-action@v1
        with:
          status: "${{ steps.tweet_text.outputs.text }}"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
