on:
  xml2json:
    url: http://www.nicovideo.jp/mylist/33014334/64875310?rss=2.0
jobs:
  tweet:
    name: Tweet Liked Videos on Niconico
    runs-on: ubuntu-latest
    steps:
      - name: Generate text
        id: tweet_text
        env:
          title: ${{ on.xml2json.outputs.title }}
          link: ${{ on.xml2json.outputs.link }}
        run: |
          tag=$(echo "${{ on.xml2json.outputs.link }}" | sed -e "s|http://www.nicovideo.jp/watch/|#|" -e "s|?ref=rss_mylist_rss2||")
          fix_link=$(echo "${{ on.xml2json.outputs.link }}" | sed -e "s/?ref=rss_mylist_rss2//")
          text=$(echo "${title} - ニコニコ動画 をマイリストに登録しました。 ${fix_link} #ニコニコ動画 ${tag}")
          echo "::set-output name=text::${text}"
