on:
  rss:
    url: https://www.nicovideo.jp/mylist/33014334/64875310?rss=atom
jobs:
  tweet:
    name: Tweet Liked Videos on Niconico
    runs-on: ubuntu-latest
    steps:
      - uses: ethomson/send-tweet-action@v1
        with:
          status: "${{ on.rss.outputs.title }} - ニコニコ動画 をマイリストに登録しました。 ${{ on.rss.outputs.link }} #ニコニコ動画"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
