on:
  script:
    run: |
      const key = "${{ secrets.RSS2JSON_API_KEY }}";
      const rss_url = "http%3A%2F%2Fwww.nicovideo.jp%2Fmylist%2F33014334%2F64875310%3Frss%3D2.0";
      const result = await helpers.axios.get(`https://api.rss2json.com/v1/api.json?api_key=${key}&rss_url=${rss_url}&count=20`);
      return result.data;
    deduplicationKey: link
    config:
      skipOnError: true
      sort:
        id: -1
jobs:
  tweet:
    name: Tweet Liked Videos on Niconico
    runs-on: ubuntu-latest
    steps:
      - name: Generate text
        id: tweet_text
        env:
          title: ${{ on.script.outputs.title }}
          link: ${{ on.script.outputs.link }}
        run: |
          fix_title=$(echo "${title}" | sed -e "s/&amp;/\&/g" | sed -e "s/&lt;/</g;s/&gt;/>/g;s/&quot;/\"/g;s/&apos;/'/g")
          fix_link=$(echo "${link}" | sed -e "s/?ref=rss_mylist_rss2//")
          tag=$(echo "${link}" | sed -e "s|http://www.nicovideo.jp/watch/|#|" -e "s|?ref=rss_mylist_rss2||")
          text=$(echo "${fix_title} - ニコニコ動画 をマイリストに登録しました。 ${fix_link} ${tag} #ニコニコ動画")
          echo "::set-output name=text::${text}"
      #- name: Text tweet
      #  uses: ethomson/send-tweet-action@v1
      #  with:
      #    status: "${{ steps.tweet_text.outputs.text }}"
      #    consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      #    consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      #    access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      #    access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      - name: Wait 5 second
        run: sleep 5s
        shell: bash
