on:
  poll:
    url:
      # マイリスト2
      - https://feed2json.redpeacock78.com/v1/feed?url=https://www.nicovideo.jp/mylist/73715852?rss=2.0&count=20
    itemsPath: items
    deduplicationKey: guid
    buildOutputsOnError: true
    config:
      skipOnError: true
jobs:
  tweet:
    name: Tweet Liked Videos on Niconico
    runs-on: ubuntu-latest
    steps:
      - name: Generate text
        id: tweet_text
        run: |
          fix_link=$(echo "${{ on.poll.outputs.link }}" | sed -e "s/?ref=rss_mylist_rss2//" | sed -e "s/www.nicovideo.jp/nicovi.deno.dev/g")
          tag=$(echo "#$(echo "${{ on.poll.outputs.guid }}" | awk -F '/' '{print $NF}')")
          text=$(echo "${{ on.poll.outputs.title }} - ニコニコ動画 をマイリストに登録しました。 ${fix_link} ${tag} #ニコニコ動画")
          echo "::set-output name=text::${text}"
      - name: Text tweet
        uses: ethomson/send-tweet-action@v1
        with:
          status: "${{ steps.tweet_text.outputs.text }}"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
