on:
  rsshub:
    path: /pixiv/user/bookmarks/17863909
  config:
    limit: 30
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rsshub.outputs.title}}
          link: ${{on.rsshub.outputs.link}}
        run: |
          echo title: $title
          echo link: $link
