on:
  rss:
    url: |
      https://rsshub-dun-zeta.vercel.app/pixiv/user/bookmarks/17863909
    config:
      skipOnError: true
jobs:
  tweet:
    name: Tweet new bookmark illustlation on Pixiv
    runs-on: ubuntu-latest
    steps:
      - name: Tweet
        run: |
          echo "Bookmarked on Pixiv: ${{ on.rss.outputs.title }} | ${{ on.rss.outputs.author }} #pixiv ${{ on.script.outputs.link }}"
