on:
  rss:
    url: |
      https://rsshub-dun-zeta.vercel.app/pixiv/user/bookmarks/17863909
    config:
      skipOnError: true
jobs:
  tweet:
    name: Tweet new bookmark illustlation on Pixiv
    runs-on: ubuntu-latest
    steps:
      - name: Tweet
        uses: ethomson/send-tweet-action@v1
        with:
          status: "Bookmarked on Pixiv: ${{ on.rss.outputs.title }} | ${{ on.rss.outputs.author }} #pixiv ${{ on.rss.outputs.link }}"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
