on:
  script:
    run: |
      const result = await helpers.axios.get("https://api.foursquare.com/v2/users/self/checkins?oauth_token=${{ secrets.SWARM_OAUTH_TOKEN }}&v=20201003");
      return result.data.response.checkins.items
    deduplicationKey: id
jobs:
  print:
    name: New checkin location tweet
    runs-on: ubuntu-latest
    steps:
      - name: Generate text
        id: tweet_text
        env:
          id: ${{ on.script.outputs.venue.id }}
          name: ${{ on.script.outputs.venue.name }}
        run: |
          if [[ "${{ on.script.outputs.venue.location.formattedAddress[1] }}" != "" ]]; then
            address=$(echo "${{ on.script.outputs.venue.location.formattedAddress[1] }}")
            text=$(echo "I'm at ${name} in ${address} https://ja.foursquare.com/v/${id}")
            echo "::set-output name=text::${text}"
          else
            address=$(echo "${{ on.script.outputs.venue.location.country }}")
            text=$(echo "I'm at ${name} in ${address} https://ja.foursquare.com/v/${id}")
            echo "::set-output name=text::${text}"
          fi
      - name: Text tweet
        uses: ethomson/send-tweet-action@v1
        with:
          status: "${{ steps.tweet_text.outputs.text }}"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
