on:
  poll:
    url: https://api.foursquare.com/v2/users/self/checkins?oauth_token=${{ secrets.SWARM_OAUTH_TOKEN }}&v=20201003
    shouldIncludeBody: true
    config:
      limit: 5
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          rawBody: ${{ toJSON(on.poll.outputs.raw__body) }}
        run: |
          echo "rawBody: $rawBody"
