on:
  script:
    run: |
      const result = await helpers.rssParser("http://www.nicovideo.jp/mylist/33014334/64875310?rss=2.0");
      return result.channel;
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.script.outputs.title}}
        run: |
          echo title: $title
