on:
  script:
    run: |
      const xml = await helpers.axios.get("http://www.nicovideo.jp/mylist/33014334/64875310?rss=2.0");
      rerurn xml;
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.script.outputs}}
        run: |
          echo title: $title
