on:
  rss:
    url: https://feed43.com/my-toggeter-favorites-item.xml
    config:
      sort:
        id: -1
jobs:
  tweet:
    name: Tweet new favorite on Toggeter
    runs-on: ubuntu-latest
    steps:
      - name: Post
        run: |
          echo "${{ on.rss.outputs.title }} ${{ on.rss.outputs.link }}"
