on:
  rss:
    url: https://feed43.com/my-toggeter-favorites-item.xml
    config:
      sort:
        id: -1
jobs:
  tweet:
    name: Tweet new favorite on Toggeter
    runs-on: ubuntu-latest
    steps:
      - name: Generate text
        id: tweet_text
        env:
          title: ${{ on.rss.outputs.title }}
          link: ${{ on.rss.outputs.link }}
        run: |
          fix_title=$(echo "${title}" | sed -e "s/&amp;/\&/g;s/&lt;/</g;s/&gt;/>/g;s/&quot;/\"/g;s/&apos;/'/g")
          text=$(echo "${fix_title} - Togetter ${link} をお気に入りにしました。 #togetter")
          echo "::set-output name=text::${text}"
      - name: Text tweet
        uses: ethomson/send-tweet-action@v1
        with:
          status: "${{ steps.tweet_text.outputs.text }}"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
