on:
  rss:
    url: https://rss.twidouga.tk/ranking
    config:
      sort:
        id: 1
      skipOnError: true

jobs:
  post:
    name: Post RSS updates to the discord
    runs-on: ubuntu-latest
    steps:
      - name: Post
        run: |
          name="${{ on.rss.outputs.title }}_$(awk -F '/' '{print $9}' <<<${{ on.rss.outputs.link }})"
          link="$(sed 's/^.*<a href=//;s/><.*$//' <<<"${{ on.rss.outputs.content }}"|tr -d \\n)"
          curl -s "${{ on.rss.outputs.link }}" --output "${name}"
          curl -s \
            -F "file1=@${name}" \
            -F "payload_json={\"content\": \"${link}\"}" \
            ${{ secrets.DISCORD_TWI_DOUGA_RANK }}
