on:
  rss:
    url: https://rss.twidouga.tk/ranking
    config:
      sort:
        id: 1
      skipOnError: true

jobs:
  post:
    name: Post RSS updates to the discord
    runs-on: ubuntu-latest
    steps:
      - name: Post
        run: |
          name="${{ on.rss.outputs.title }}_$(awk -F '/' '{print $NF}' <<<${{ on.rss.outputs.link }})"
          link="$(awk -F '=' '{sub("><img src","",$2);print $2}' <<<"${{ on.rss.outputs.content }}"|tr -d \\n)"
          {
            aria2c -q -x5 "${{ on.rss.outputs.link }}" -o "${name}"
            type=$(awk -F ',' '{print $1}' <<<$(file -b "./${name}"))
            if [[ "${type}" == "ISO Media" ]]; then
              curl -s \
                -F "file1=@${name}" \
                -F "payload_json={\"content\": \"${link}\"}" \
                ${{ secrets.DISCORD_TWI_DOUGA_RANK }}
            fi
          } || exit 0
