on:
  twitter:
    api: statuses/user_timeline
    auth:
      consumer_key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      consumer_secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    params:
      screen_name: kazuki_199778
      tweet_mode: "extended"
    config:
      sort:
        id: 1
jobs:
  webhook:
    name: New Tweet to Toot
    runs-on: ubuntu-latest
    steps:
      - name: Tweet URI encode
        id: encode_tweet
        run: |
          if [[ "${{ on.twitter.outputs.retweeted_status.full_text }}" != "" ]]; then
            encode_text=$(echo 'RT @${{ on.twitter.outputs.retweeted_status.user.screen_name }}: ${{ on.twitter.outputs.retweeted_status.full_text }}' | sed "s/&amp;/\&/g" | od -An -vtx1 | awk 'BEGIN{ORS=""}{gsub(" ", "%", $0);print toupper($0)}')
            echo "::set-output name=encoded_text::${encode_text}"
          else
            encode_text=$(echo '${{ on.twitter.outputs.full_text }}' | sed "s/&amp;/\&/g" | od -An -vtx1 | awk 'BEGIN{ORS=""}{gsub(" ", "%", $0);print toupper($0)}')
            echo "::set-output name=encoded_text::${encode_text}"
          fi
      - name: Tweet to Toot
        uses: actionsflow/axios@v1
        with:
          url: https://mstdn.jp/api/v1/statuses
          method: POST
          content-type: application/x-www-form-urlencoded
          data: "access_token=${{ secrets.MASTDON_ACCESS_TOKEN }}&status=${{ steps.encode_tweet.outputs.encoded_text }}&visibility=public"
