on:
  twitter:
    api: statuses/user_timeline
    auth:
      consumer_key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      consumer_secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    params:
      screen_name: kazuki_199778
      tweet_mode: "extended"
jobs:
  webhook:
    name: New Tweet to Toot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tweet URI encode
        id: encode_tweet
        run: |
          encode_text=$(ruby -r cgi -e "puts CGI.escape(\""${{ on.twitter.outputs.full_text }}"\")")
          echo "::set-output name=encoded_text::${encode_text}"
          echo ${encode_text}
      - name: Tweet to Toot
        uses: actionsflow/axios@v1
        with:
          url: https://mstdn.jp/api/v1/statuses
          method: POST
          content-type: application/x-www-form-urlencoded
          data: "access_token=${{ secrets.MASTDON_ACCESS_TOKEN }}&status=${{ steps.encode_tweet.outputs.encoded_text }}&visibility=public"
