on:
  twitter:
    api: statuses/user_timeline
    auth:
      consumer_key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      consumer_secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    params:
      screen_name: kazuki_199778
      include_rts: true
jobs:
  webhook:
    name: New Tweet to Toot
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: |
          apt update
          apt install nkf
      - name: Tweet URI encode
        run: |
          encode_text="$(echo ${{ on.twitter.outputs.full_text }} | nkf -WwMQ | sed 's/=$//g' | tr = % | tr -d '\\n')"
          echo "::set-output name=encoded_text::${encode_text}"
          echo ${encode_text}
        id: encode_tweet
      - name: Tweet to Toot
        uses: actionsflow/axios@v1
        with:
          url: https://mstdn.jp/api/v1/statuses
          method: POST
          content-type: application/x-www-form-urlencoded
          data: "access_token=${{ secrets.MASTDON_ACCESS_TOKEN }}&status=${{ steps.encode_tweet.outputs.encoded_text }}&visibility=public"
