on:
  twitter:
    api: statuses/user_timeline
    auth:
      consumer_key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      consumer_secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    params:
      screen_name: kazuki_199778
      include_rts: true,
      tweet_mode: "extended"
jobs:
  webhook:
    name: New Tweet to Toot
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: |
          apt update
          apt install nkf
      - name: Tweet URI encode
        id: encode_tweet
        run: |
        if $(echo "${{ on.twitter.outputs.full_text }}" | grep -q "RT @.*: "); then
          rt_text=$(echo "${{ on.twitter.outputs.full_text }}" | sed -e "s/RT @.*: /${{ on.twitter.outputs.retweeted_status.text }}/")
          encode_text=$(echo "${rt_text}" | while read -r line; do echo "${line}" | nkf -W8MQ | sed 's/=$//' | tr '=' '%' | paste -s -d '\0' - | sed -e 's/%7E/~/g' -e 's/%5F/_/g' -e 's/%2D/-/g' -e 's/%2E/./g'; done)
          encode_text="${encode_text//$'\n'/%0A}"
          echo "::set-output name=encoded_text::${encode_text}"
        else
          encode_text=$(echo "${{ on.twitter.outputs.full_text }}" | while read -r line; do echo "${line}" | nkf -W8MQ | sed 's/=$//' | tr '=' '%' | paste -s -d '\0' - | sed -e 's/%7E/~/g' -e 's/%5F/_/g' -e 's/%2D/-/g' -e 's/%2E/./g'; done)
          encode_text="${encode_text//$'\n'/%0A}"
          echo "::set-output name=encoded_text::${encode_text}"
        fi
      - name: Tweet to Toot
        uses: actionsflow/axios@v1
        with:
          url: https://mstdn.jp/api/v1/statuses
          method: POST
          content-type: application/x-www-form-urlencoded
          data: "access_token=${{ secrets.MASTDON_ACCESS_TOKEN }}&status=${{ steps.encode_tweet.outputs.encoded_text }}&visibility=public"
