on:
  rss:
    url: https://script.google.com/macros/s/AKfycbx-WwG_YOQd5AycMbSYOAD-43Eoi_OM0HV4-tVkJ-eq9w-52Q/exec
jobs:
  tweet:
    name: Tweet Liked Videos on Youtube
    runs-on: ubuntu-latest
    steps:
      - name: Generate text
        id: tweet_text
        env:
          title: ${{ on.rss.outputs.title }}
          link: ${{ on.rss.outputs.link }}
        run: |
          fix_title=$(echo "${title}" | sed -e "s/&amp;/\&/g;s/&lt;/</g;s/&gt;/>/g;s/&quot;/\"/g;s/&apos;/'/g")
          text=$(echo "Liked on YouTube: ${fix_title} ${link}")
          echo "::set-output name=text::${text}"
      - uses: ethomson/send-tweet-action@v1
        with:
          status: "${{ steps.tweet_text.outputs.text }}"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
