on:
  rss:
    url: https://zenn.dev/feed
    config:
      skipOnError: true
jobs:
  post:
    name: Post RSS updates to the discord
    runs-on: ubuntu-latest
    steps:
      - name: Fix data
        id: fix
        run: |
          fix_title=$(echo "${{ on.rss.outputs.title }}" | sed -e "s/&amp;/\&/g;s/&lt;/</g;s/&gt;/>/g;s/&quot;/\"/g;s/&apos;/'/g" | sed -e 's/*/\\\\*/g;s/_/\\\\_/g;s/~~/\\\\~~/g')
          echo "::set-output name=title::${fix_title}"
      - name: Post
        run: |
          curl -s \
               -X POST \
               -H  "Content-Type: application/json" \
               -d '{"content": "**${{ steps.fix.outputs.title }}** - ${{ on.rss.outputs.pubDate }} ${{ on.rss.outputs.link }}"}' \
               ${{ secrets.DISCORD_TECH_ZENN_ZENN_TREND }}
          sleep 5
